from build.wrapper import aao_generator

aao_generator(th_opt=5,
              flag_ehel=1,
              reg1=0.1,
              reg2=0.1,
              reg3=0.2,
              reg4=0.2,
              npart=3,
              epirea=3,
              mm_cut=0.2,
              t_targ=5.0,
              r_targ=0.5,
              vertex_x=0.0,
              vertex_y=0.0,
              vz=0.0,
              ebeam=4.8,
              q2_min=0.9,
              q2_max=3.5,
              ep_min=0.1,
              ep_max=4.25,
              delta=0.0, nmax=500,
              fmcall=0.0,
              sigr_max=0.005,
              file_out=b"aao_rad.lund")
