#!/usr/bin/env bash
# Build the validation driver build/dump_sigma.
#
# sigma() lives in src/aao_rad.f90, which is a *program* and therefore not part
# of libaao_libs.a.  Rather than copy it -- and risk the copy drifting away from
# the original -- this script lifts the function text verbatim out of
# aao_rad.f90 and concatenates it with the driver before compiling.
#
# Usage: validation/build_dump_sigma.sh [build-dir]
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(dirname "$here")"
build="${1:-$root/build}"
out="$build/dump_sigma_generated.f90"

mkdir -p "$build"

python3 - "$root/src/aao_rad.f90" "$here/dump_sigma_main.f90" "$out" <<'PY'
import re, sys
src, driver, out = sys.argv[1:4]
lines = open(src).read().split("\n")
start = next(i for i, l in enumerate(lines) if re.match(r"^real function sigma\(", l))
end = next(i for i in range(start, len(lines)) if lines[i].strip().lower() == "end")
with open(out, "w") as fh:
    fh.write("! GENERATED by validation/build_dump_sigma.sh -- do not edit.\n")
    fh.write(f"! sigma() extracted verbatim from src/aao_rad.f90 lines {start + 1}-{end + 1}\n\n")
    fh.write("\n".join(lines[start:end + 1]))
    fh.write("\n\n")
    fh.write(open(driver).read())
print(f"extracted src/aao_rad.f90:{start + 1}-{end + 1}")
PY

gfortran -O2 -g -I"$root/src" \
    "$out" "$build/libaao_libs.a" -o "$build/dump_sigma"
echo "built $build/dump_sigma"
