#!/usr/bin/env bash
# Build the validation driver build/dump_soft.
#
# The soft branch (the ek < delta half of the integrand) lives inside the main
# program in src/aao_rad.f90, so it is not part of libaao_libs.a.  Rather than
# copy it -- and risk the copy drifting away from the original -- this script
# lifts the block verbatim out of aao_rad.f90 and wraps it in a subroutine that
# validation/dump_soft_main.f90 declares.  The block's two `go to` statements
# get the labels 20 (reject) and 28 (accept) at the end of the wrapper, which
# is exactly where they lead in the original.
#
# Usage: validation/build_dump_soft.sh [build-dir]
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(dirname "$here")"
build="${1:-$root/build}"
out="$build/dump_soft_generated.f90"

mkdir -p "$build"

python3 - "$root/src/aao_rad.f90" "$here/dump_soft_main.f90" "$out" <<'PY'
import sys

src, driver, out = sys.argv[1:4]
lines = open(src).read().split("\n")

# The soft branch opens with the dsigma() call that replaces the radiative
# sigma() on the ek < delta side, and ends with the test that decides whether
# the trial survives.  Start there rather than at the comment banner, so that
# the `if (ek .lt. delta) then` / `intreg = 6` wrapper stays in aao_rad.f90 --
# the generated subroutine *is* the ek < delta case.
start = next(i for i, l in enumerate(lines)
             if l.strip().startswith("call dsigma(th0, qsq, epw,"))
end = next(i for i in range(start, len(lines))
           if lines[i].strip() == "sigr = sigr1 / delta / 4. / pi")
end = next(i for i in range(end, end + 8) if lines[i].strip() == "endif")
block = [l for l in lines[start:end + 1] if l.strip()]


def lift(header):
    """Lift a whole function out of the main program, verbatim."""
    i = next(k for k, l in enumerate(lines)
             if l.strip().lower().startswith(header.lower()))
    j = next(k for k in range(i, len(lines))
             if lines[k].strip().lower() == "end")
    return lines[i:j + 1]


# spence() and its two 100-step quadrature helpers are also inside the main
# program, so the library does not have them either.  They matter: spence() uses
# its own single-precision `pi = 3.14159` and sintp/sintn are Riemann sums
# accumulated in float32, so deltar cannot be reproduced from a float64
# implementation of the same integral.
helpers = lift("real function spence(") + [""] \
    + lift("real function sintp(") + [""] \
    + lift("real function sintn(")

preamble = """! GENERATED by validation/build_dump_soft.sh -- do not edit.
!
! The soft branch lifted verbatim from src/aao_rad.f90 lines {lo}-{hi}.
! Declaration kinds mirror aao_rad.f90's main program: es, ep, ps, pp and cst0
! come from COMMON /radcal/ and are real*8, while q0, s, th0, qsq, epw, w2,
! sp, csthcm, phicm, f, g, fkt, kfac, nu, epeps, signr, deltar, delinf and
! sigr1 are single precision.  That is not cosmetic: sp and w2 are rounded to
! float32 before they reach the logarithms and the pion kinematic factor, so a
! float64 replica would not reproduce the original.
!
! The block names th_opt, epirea and res_opt.  Those live in COMMON /ALPHA/ in
! the original as well (aao_rad.f90:210 reads theory_opt into TH_OPT, :218
! reads res_opt into RES_OPT), so the wrapper uses the COMMON entities directly
! instead of shadowing them with locals -- Fortran is case insensitive and
! would reject the duplicate declaration.

subroutine soft_branch(es, ep, qs, csthcm, phicm, ehel, sigr, sigr1, &
   sigma0, sigu, sigt, sigl, sigi, sigip, asym_p, f, g, fkt, kfac, nu, &
   epeps, signr, deltar, delinf, log2sp, w2)

   implicit none
   COMMON/ALPHA/ ALPHA, PI, MP, MPI, MEL, WG, EPIREA, TH_OPT, RES_OPT

   real*8 ALPHA, PI, MP, MPI, MEL, WG, es, ep, ps, pp, cst0, delta
   integer EPIREA, TH_OPT, RES_OPT, ehel
   real qs, csthcm, phicm, spence
   real th0, qsq, epw, w2, q0, s, sp, epeps, kfac, nu, f, g, fkt
   real signr, x1, x2, s1, s2, deltar, delinf, sigr1, sigr, log2sp
   real sigma0, sigu, sigt, sigl, sigi, sigip, asym_p

   ! aao_rad.f90:584-620 computes these before reaching the soft branch.
   delta = 0.005d0
   s = qs / 4. / es / ep
   th0 = 2. * asin(sqrt(s))
   cst0 = cos(th0)
   q0 = es - ep
   qsq = qs
   w2 = MP**2 + 2. * MP * q0 - qs
   epw = sqrt(w2)
   ps = sqrt(es**2 - MEL**2)
   pp = sqrt(ep**2 - MEL**2)
   sp = es * ep - ps * pp * cst0

""".format(lo=start + 1, hi=end + 1)

epilogue = """

!     aao_rad.f90:883 -- `go to 28` lands on the phase-space factors, which is
!     as far as the cross section is concerned.
28  sigr = sigr1 / delta / 4. / pi
   log2sp = dlog(2. * sp / MEL**2)
   return

!     aao_rad.f90:801 and :885 -- `go to 20` abandons the trial.
20  sigr = -1.
   sigr1 = -1.
   f = -1.
   g = -1.
   fkt = -1.
   kfac = -1.
   nu = -1.
   epeps = -1.
   signr = -1.
   deltar = -1.
   delinf = -1.
   log2sp = -1.
   return

   end subroutine soft_branch


"""

with open(out, "w") as fh:
    fh.write(preamble)
    fh.write("\n".join(block))
    fh.write(epilogue)
    fh.write("\n".join(helpers))
    fh.write("\n\n")
    fh.write(open(driver).read())
print(f"extracted src/aao_rad.f90:{start + 1}-{end + 1} "
      "(plus spence/sintp/sintn)")
PY

gfortran -O2 -g -I"$root/src" \
    "$out" "$build/libaao_libs.a" -o "$build/dump_soft"
echo "built $build/dump_soft"